#pragma once

#define DUCKDNS_DOMAIN "watermanager"
#define DUCKDNS_TOKEN  "YOUR_REAL_DUCKDNS_TOKEN"

#define WEB_USERNAME   "admin"
#define WEB_PASSWORD   "YOUR_STRONG_PASSWORD"

#define AP_SSID        "ESP32-WaterMonitor"
#define AP_PASSWORD    "YOUR_STRONG_AP_PASSWORD"

#define TELEGRAM_BOT_TOKEN "YOUR_BOT_TOKEN"
#define TELEGRAM_CHAT_ID   "YOUR_CHAT_ID"